### ISSUE TITLE
Could the CF search also search the standard name aliases ?

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#59] opened 2018-03-16 15:40 UTC
_The functionality discussed in this issue has been implemented by @bzah in_ [this pull request](https://github.com/cf-convention/cf-convention.github.io/pull/218).

When I go to the [CF Standard Name Table](http://cfconventions.org/Data/cf-standard-names/50/build/cf-standard-name-table.html) page and search the standard name used for **psl** in the CMIP6 Data Request (DR 01.00.22), **air_pressure_at_sea_level**, I get `Found 0 standard names matching query: air_pressure_at_sea_level`, which led me to believe that there was an error in the name, or that I should not use underline characters in the names, when searching

Now, if I look for **air_pressure_at_mean_sea_level**, I get **psl**, `Found 1 standard names matching query: air_pressure_at_mean_sea_level` and also the following information 
```
air_pressure_at_mean_sea_level
alias: air_pressure_at_sea_level
```

I could be useful if the search could search both the main/canonical (or whatever you call these) names **and the aliases**

I don't know if this one is also for @mattben , or for somebody else working on the Search

**Comment by JonathanGregory** [comment] 2021-09-21 17:58
I agree with Daniel @erget that this seems to have been neglected, but it's still true and it's a reasonable point. I wonder whether Fran @feggleton or Alison @japamment could comment - would it be easy to make the "search" on the standard name table apply to the aliases as well as the standard names?

**Comment by bzah** [comment] 2022-07-21 18:34
I'm not sure who to ping but there is a short PR solving this issue: #218 
Also, if this one get reviewed, I'm willing to try to implement a fix for #200 as well (in a separate PR).

**Comment by JonathanGregory** [comment] 2022-10-26 15:03
Dear Abel @bzah 

Thanks for providing a fix for this issue. Are you able to present your modified version on the web (using GitHub pages, for instance), so we can try it out?

I am not the right person to review the code because I don't know javascript. It would be very helpful if someone who knows javascript could kindly look at https://github.com/cf-convention/cf-convention.github.io/pull/218, which modifies the standard name page so that it can search aliases too.

Best wishes

Jonathan

**Comment by feggleton** [comment] 2022-10-26 15:51
Apologies for not commenting on this in the past. I think searching on alias and/or unit would be 2 very useful bits of functionality. Thank you for providing a fix for the alias searching and if you have the time/ability to add search by units that would be amazing.

**Comment by bzah** [comment] 2022-10-27 12:11
I deployed my fork's git branch (enh/alias-search) on my github page: https://bzah.github.io/cf-convention.github.io/Data/cf-standard-names/current/build/cf-standard-name-table.html 
Careful, some links may be broken due to how it's deployed.

To test the search for aliases you can try "aerosol_angstrom_exponent" on the search bar and the table should update with 
"angstrom_exponent_of_ambient_aerosol_in_air" only.

Thank you @JonathanGregory for suggesting to use github page, I never paid too much attention to that feature before, but it's quite powerful indeed.

**Comment by JonathanGregory** [comment] 2022-10-27 15:08
@sadielbartholomew: I am sure your review would be useful! Thanks.

@bzah: Thanks for putting it on GitHub pages, which is a useful facility, I agree. (I learned about it myself only recently from other CF discussions.) The alias search works fine for me. I wonder whether you could make searching aliases _optional_ with a check box, perhaps switched on by default?

Jonathan

**Comment by bzah** [comment] 2022-10-28 14:57
> I wonder whether you could make searching aliases optional with a check box, perhaps switched on by default?

Done. See the [demonstrator](https://bzah.github.io/cf-convention.github.io/Data/cf-standard-names/current/build/cf-standard-name-table.html).

**Comment by feggleton** [comment] 2022-10-31 10:14
Thanks for taking the time to create this @bzah. Flagging to @japamment as I'm sure she would like to review as well

**Comment by japamment** [comment] 2022-11-14 13:25
Apologies for coming in late on this - I just saw the latest comment from @JonathanGregory and had a look at the pull request. @bzah I am fine in principle with us adding the alias search, but the pull request appears to be editing the html standard name table directly, so I fear this is not a robust way of applying the change.

The issue is that updates to the standard name table are not applied via pull requests on GitHub. The publishing process for standard names not only produces the XML and HTML versions of the table, but also produces the names in a format suitable for ingestion into the NERC Vocabulary Server (NVS2). Because of these publishing needs, the XML file is created by an external editor which sits on top of a database of all the existing standard names and description text. I then use an XSLT script (see, for example [https://github.com/cf-convention/cf-convention.github.io/blob/main/Data/cf-standard-names/79/xsl/html/cf-standard-name-table-1.3.xsl](https://github.com/cf-convention/cf-convention.github.io/blob/main/Data/cf-standard-names/79/xsl/html/cf-standard-name-table-1.3.xsl) to generate the HTML file from the XML file. If the extra code to search aliases were added to the XSLT file, the same processing can be applied to all new versions of the standard name table and even retrospectively to older versions if that would be useful.

I'm afraid I have not reviewed the code in detail, but would it work with the XSLT approach?

**Comment by bzah** [comment] 2022-11-14 18:22
Hi @japamment, I guessed there was some hidden magic to generate the htmI, thanks for pointing it out.
> but would it work with the XSLT approach?

I think so yes. The search aIias onIy needs modification of the js within `script` tags and the adding of a new checkbox to enabIe/disabIe itseIf.
Thus the xsIt scripts must be changed in order to generate this updated javascript snippet, and to generate the new htmI checkbox.

Is their a _master_ xsIt script somewhere that wouId propagate modifications ? Or do you need to update the xsI fiIe of each version ?

**Comment by japamment** [comment] 2022-11-25 10:02
Hi @bzah, currently there isn't a master xslt script. However, if your pull request applies the changes to the latest version (79) it would not be too onerous a task for me to reprocess earlier versions, and it would of course be carried forward into subsequent versions.

I agree with the earlier comment by @feggleton that it would be great if the search could be expanded to include canonical units as well as aliases (this has been suggested in issue [#200](https://github.com/cf-convention/cf-convention.github.io/issues/200). If this could also be added to the xslt script I would be able to reprocess all versions of the standard name table to add both features. (If it's not possible to add the units search at the same time then we can continue to discuss that issue separately).

Best wishes
Alison

**Comment by JonathanGregory** [comment] 2022-12-05 08:56
21 days ago I wrote

> I think that we can accept this useful enhancement to the website in a week from now (5 Dec) since two weeks have already passed since the last comment

but Alison @japamment provided some essential further information meaning that some further work is needed to make the change future-proof. Everyone agrees that this enhancement would be valuable, and likewise the [related change regarding `units`](https://github.com/cf-convention/cf-convention.github.io/issues/200). Thank you for your work on these matters, @bzah.

Jonathan

**Comment by larsbarring** [comment] 2023-04-28 09:38
cf. [#200_comment](https://github.com/cf-convention/cf-convention.github.io/issues/200#issuecomment-1527132337)

**Closed** 2023-07-06 09:06 UTC
Labels: enhancement, new contributor to IM&W
