### ISSUE TITLE
Missing Trac Wiki pages

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/cf-convention.github.io#205] opened 2022-01-13 19:04 UTC
The archive of old Trac tickets (/Data/Trac-tickets) contains links to the old Trac Wiki content ("/trac/wiki/...") but it doesn't look like the wiki content was archived here. Does anyone know if that content is still available/backed-up somewhere so we could grab it and archive it here?

**Comment by larsbarring** [comment] 2022-01-13 22:09
Hi Ethan,
They are archived [here](https://github.com/cf-convention/cf-convention.github.io/tree/main/Data/Trac-tickets), but not easily found. I just happened to come across then some time ago in issue comment. 

Maybe it would be useful to have a link somewhere.
/Lars

**Comment by larsbarring** [comment] 2022-01-13 22:12
... and then there is already:
http://cfconventions.org/discussion.html
And here are links to the email archive, too.

**Comment by JonathanGregory** [comment] 2022-01-14 12:23
The wiki page on grid-mapping <> WKT translation was converted to HTML and are at http://cfconventions.org/wkt-proj-4.html, which is linked from the conventions page. It would be fortunate if that's the one you want. Jonathan

**Comment by taylor13** [comment] 2022-01-14 15:53
Hi @ethanrd -  If Jonathan hasn't provided enough of a lead on this and if Jeff doesn't see this, I'll try to find out if the pages are still around.  I think it is unlikely that Jeff lost anything in the transfer.
Karl

**Comment by ethanrd** [comment] 2022-01-15 00:17
Thanks @JonathanGregory and @taylor13 - I don't have a particular need for any of the old Trac Wiki pages. I was looking at some old conversations for mention of vertical CRSs and noticed that the Trac Wiki pages weren't available. So I was asking more with an eye towards completeness.

I'm seeing reference to 21 unique Trac Wiki pages in the Trac Tickets archive. Not sure if there are more than that or how useful they might really be going forward. But if we can find them and get them up on the web site alongside the Trac Tickets, I think that would be good.

@taylor13 - If you do find the pages, I'm happy to take a first crack at getting them on the website.

**Comment by ethanrd** [comment] 2022-09-29 23:05
Hi @taylor13 - Just circling back around to this. Did you get a chance to check whether the old CF Trac Wiki pages might be available somewhere? There are a few references in the FAQ as well as in some of the Trac tickets.

**Comment by taylor13** [comment] 2022-09-30 17:38
I'll look into this now.  Ping me if for some reason I go silent again.

**Comment by ethanrd** [comment] 2022-09-30 20:47
Thanks Karl @taylor13 !

**Comment by painter1** [comment] 2022-10-01 02:21
The old CF Trac Wiki pages still exist, hidden inside a database.  It can be accessed by people who have a su login to the LLNL computer containing the database.  I emailed Chris Mauzey, Karl Taylor, and Paul Durack with some details.

**Comment by ethanrd** [comment] 2022-10-03 20:45
Thanks Jeff! @painter1

**Comment by taylor13** [comment] 2022-12-08 15:30
**Below is the information Jeff sent me by email.  I am unfamiliar with much of this, but please let me know how PCMDI can help.**
__

Almost the last thing I did with CF was to migrate the ticket data which appears to be in /usr/local/trac-1.0/cf/files/attachments/ticket.  I missed the wiki and the whole issue of external links from the Trac issue tracker.
I did migrate the wiki links which came from the CF Conventions document itself, but not the whole wiki.  That was an oversight which came because I was focused on the document rather than the wiki.  The new location is [https://github.com/cf-convention/cf-conventions/wiki](https://urldefense.us/v3/__https:/github.com/cf-convention/cf-conventions/wiki__;!!G2kpM7uM-TzIFchu!k9CeuCTUL8bXBh8K_hNKieJoaXbH3hXTBinsQmNuSBw7-md9R3JwablNwr_i81ht380$)   .

But the migration is tricky, you can't actually use /usr/local/trac-1.0/cf/files/attachments/....  The problem is that this has a bunch of files named after their own checksums!  The contents of the files aren't useful AFAIK, and nothing points to those files.  Instead I had to extract the text out of the database.  I don't remember for sure, but looking at it now I think that the text is marked-up ASCIDoc, so extracting the text actually gives you the formatting too.

Here is roughly how I extracted the few wiki files I had gotten before, as it could be applied to the data model.   To get everything would use the same principle but with more complexity.

On pcmdi6:
sudo sqlite3 env/cf/db/trac.db
sqlite> .schema wiki                           # just to get oriented
sqlite> SELECT name FROM wiki;    # to see the file names
sqlite> SELECT version FROM wiki WHERE name='markhDataModelDraft';  # we only want the latest
sqlite> SELECT text FROM wiki WHERE name='markhDataModelDraft' AND version=10;

Of course you can direct the text output to a file and there is a lot more to do. e.g. editing the links to point to the newly created files (instead of going through a Trac script  which unpacks the database).

**Comment by JonathanGregory** [comment] 2022-12-08 17:53
Chris @mauzey1 's files are a good basis. Thanks very much, Chris! I have created a [pull request](https://github.com/cf-convention/cf-convention.github.io/pull/314) to merge them in the repo.

**Comment by JonathanGregory** [comment] 2023-01-06 13:44
I have merged my own PR, to make [this copy](https://github.com/cf-convention/cf-convention.github.io/tree/main/Data/wiki) of the trac wiki that was kindly rescued by Karl @taylor13's colleague Chris @mauzey1. We will need to make new links manually where relevant and useful.

**Closed** 2023-09-27 12:42 UTC
Labels: defect, new contributor to IM&W
